version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: comp3123_assignment2

  backend:
    build:
      context: ./server
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      DB_CONNECTION_STRING: "mongodb+srv://dbking:PN45TKjJLjYX3zlW@cluster0.qggx7lx.mongodb.net/comp3123_assigment1?retryWrites=true&w=majority"

  frontend:
    build:
      context: ./client
    ports:
      -  "8080:80"
    depends_on:
      - server